#@token = 14d72b99-48f6-48d3-94d3-5a4dcfd96c81
//@token = 21418bc8-68ba-41ec-9045-036f1a308fde
@token = 902ace23-a26c-464e-ba88-a44cd5450c8f

### Search events by popularity
GET  http://localhost:1904/events/popular/?s=5&p=2

### Search events by name
GET  http://localhost:1904/events/?name=football

### Create user
POST http://localhost:1904/users
Content-Type: application/json

{
    "username": "asds2133" 
}

### create group no auth
POST http://localhost:1904/groups
Content-Type: application/json

{
    "name": "teste1",
    "description": "grupo teste" 
}
### create group with auth
POST http://localhost:1904/groups
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "teste3",
    "description": "grupo teste" 
}

### get group with auth
GET http://localhost:1904/group/53f4fb9a-c05e-494d-b1c9-82ca6ffa03fc
Content-Type: application/json
Authorization: Bearer {{token}}




### update group with auth
PUT http://localhost:1904/group/53f4fb9a-c05e-494d-b1c9-82ca6ffa03fc
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "updatetest1",
    "description": "grupoupdated" 
}


### add event to group
PUT http://localhost:1904/group/53f4fb9a-c05e-494d-b1c9-82ca6ffa03fc/events
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": "G5dIZ9YmSXKWz"
}

### Delete event from group
DELETE http://localhost:1904/group/677d805a-cf7e-4fc4-a130-e9653927d6aa/events/G5dIZ9YmSXKWz
Content-Type: application/json
Authorization: Bearer {{token}}


### Get all groups
GET http://localhost:1904/groups
Authorization: Bearer {{token}}

### Delete group
DELETE http://localhost:1904/group/5a53ebe3-4f88-44cf-9f60-f07704b46dde
Content-Type: application/json
Authorization: Bearer {{token}}


